---
  flash:
    app-start-page: 0
  fuses:
    unlock: 0xFF
    lock: 0xEF
    ext: 0xF8
    high: 0xD0
    low: 0xFF
  usb:
    endpoints:
      size:
        control: 8
        midi-in-out: 32
      midi:
        in: 0x81
        out: 0x02
  uart:
    buffers:
      tx: 64
      rx: 64
  i2c:
    buffers:
      tx: 64
      rx: 64