---
  mcu: "stm32f405rg"
  extClockMhz: 16
  usb: true
  uart:
    touchscreen:
      channel: 0
      components: 64
  buttons:
    type: "native"
    extPullups: true
    pins:
    -
      port: "B"
      index: 7
    -
      port: "B"
      index: 6
    -
      port: "B"
      index: 9
    -
      port: "B"
      index: 8
    -
      port: "B"
      index: 1
    -
      port: "B"
      index: 0
    -
      port: "B"
      index: 11
    -
      port: "B"
      index: 10
  analog:
    type: "4067"
    inputVoltage: "3.3"
    multiplexers: 1
    pins:
      s0:
        port: "A"
        index: 5
      s1:
        port: "A"
        index: 4
      s2:
        port: "A"
        index: 7
      s3:
        port: "A"
        index: 6
      z0:
        port: "C"
        index: 5
    indexing:
    - 10
    - 11
    - 12
    - 13
    - 8
    - 9
    - 14
    - 15
    - 7
    - 6
    - 1
    - 0
    - 5
    - 4
    - 3
    - 2