---
  mcu: "stm32f405rg"
  extClockMhz: 16
  usb: true
  buttons:
    type: "shiftRegister"
    shiftRegisters: 3
    pins:
      data:
        port: "B"
        index: 13
      clock:
        port: "B"
        index: 15
      latch:
        port: "B"
        index: 14
    indexing:
    - 20
    - 21
    - 23
    - 22
    - 17
    - 16
    - 19
    - 18
    - 12
    - 13
    - 15
    - 14
    - 9
    - 8
    - 11
    - 10
    - 4
    - 5
    - 7
    - 6
    - 1
    - 0
    - 3
    - 2
  analog:
    extReference: false
    type: "4067"
    inputVoltage: "3.3"
    multiplexers: 4
    pins:
      s0:
        port: "B"
        index: 5
      s1:
        port: "B"
        index: 6
      s2:
        port: "B"
        index: 4
      s3:
        port: "B"
        index: 3
      z0:
        port: "A"
        index: 7
      z1:
        port: "A"
        index: 6
      z2:
        port: "A"
        index: 5
      z3:
        port: "A"
        index: 1
    indexing:
    - 42
    - 43
    - 44
    - 45
    - 50
    - 40
    - 41
    - 46
    - 47
    - 62
    - 39
    - 38
    - 33
    - 32
    - 58
    - 37
    - 36
    - 35
    - 34
    - 53
    - 26
    - 27
    - 28
    - 29
    - 49
    - 24
    - 25
    - 30
    - 31
    - 61
    - 23
    - 22
    - 17
    - 16
    - 57
    - 21
    - 20
    - 19
    - 18
    - 54
    - 10
    - 11
    - 12
    - 13
    - 48
    - 8
    - 9
    - 14
    - 15
    - 60
    - 7
    - 6
    - 1
    - 0
    - 56
    - 5
    - 4
    - 3
    - 2
    - 55
  leds:
    external:
      type: "shiftRegister"
      shiftRegisters: 3
      invert: true
      pins:
        data:
          port: "B"
          index: 2
        clock:
          port: "B"
          index: 0
        latch:
          port: "B"
          index: 1
        enable:
          port: "B"
          index: 10
      indexing:
      - 3
      - 7
      - 4
      - 0
      - 5
      - 1
      - 6
      - 2
      - 11
      - 15
      - 12
      - 8
      - 13
      - 9
      - 14
      - 10
      - 19
      - 23
      - 20
      - 16
      - 21
      - 17
      - 22
      - 18
  bootloader:
    button:
      port: "D"
      index: 2