---
  mcu: "stm32f405rg"
  extClockMhz: 8
  usb: true
  buttons:
    type: "shiftRegister"
    shiftRegisters: 4
    encoders: false
    pins:
      data:
        port: "C"
        index: 7
      clock:
        port: "B"
        index: 13
      latch:
        port: "B"
        index: 14
    indexing:
    - 29
    - 26
    - 28
    - 27
    - 30
    - 25
    - 31
    - 24
    - 21
    - 18
    - 20
    - 19
    - 22
    - 17
    - 23
    - 16
    - 13
    - 10
    - 12
    - 11
    - 14
    - 9
    - 15
    - 8
    - 5
    - 2
    - 4
    - 3
    - 6
    - 1
    - 7
    - 0
  analog:
    type: "4067"
    inputVoltage: "3.3"
    multiplexers: 5
    pins:
      s0:
        port: "A"
        index: 9
      s1:
        port: "A"
        index: 8
      s2:
        port: "C"
        index: 9
      s3:
        port: "C"
        index: 8
      z0:
        port: "A"
        index: 3
      z1:
        port: "A"
        index: 4
      z2:
        port: "A"
        index: 5
      z3:
        port: "A"
        index: 6
      z4:
        port: "A"
        index: 7
    indexing:
    - 10
    - 11
    - 12
    - 13
    - 72
    - 8
    - 9
    - 14
    - 15
    - 73
    - 7
    - 6
    - 1
    - 0
    - 74
    - 5
    - 4
    - 3
    - 2
    - 75
    - 26
    - 27
    - 28
    - 29
    - 76
    - 24
    - 25
    - 30
    - 31
    - 77
    - 23
    - 22
    - 17
    - 16
    - 78
    - 21
    - 20
    - 19
    - 18
    - 79
    - 42
    - 43
    - 44
    - 45
    - 64
    - 40
    - 41
    - 46
    - 47
    - 65
    - 39
    - 38
    - 33
    - 32
    - 66
    - 37
    - 36
    - 35
    - 34
    - 67
    - 58
    - 59
    - 60
    - 61
    - 68
    - 56
    - 57
    - 62
    - 63
    - 69
    - 55
    - 54
    - 49
    - 48
    - 70
    - 53
    - 52
    - 51
    - 50
    - 71
  leds:
    external:
      type: "max7219"
      drivers: 1
      invert: false
      pins:
        data:
          port: "C"
          index: 6
        clock:
          port: "B"
          index: 12
        latch:
          port: "B"
          index: 15
      indexing:
      - 7
      - 3
      - 47
      - 43
      - 15
      - 11
      - 55
      - 51
      - 39
      - 35
      - 23
      - 19
      - 63
      - 59
      - 31
      - 27
      - 30
      - 26
      - 62
      - 58
      - 22
      - 18
      - 38
      - 34
      - 54
      - 50
      - 14
      - 10
      - 46
      - 42
      - 6
      - 2
  bootloader:
    button:
      port: "C"
      index: 5
      activeState: "low"