---
  mcu: "stm32f411ce"
  extClockMhz: 25
  usb: true
  buttons:
    type: "shiftRegister"
    shiftRegisters: 4
    encoders: false
    pins:
      data:
        port: "B"
        index: 15
      clock:
        port: "B"
        index: 2
      latch:
        port: "B"
        index: 1
    indexing:
    - 31
    - 24
    - 30
    - 25
    - 29
    - 26
    - 28
    - 27
    - 23
    - 16
    - 22
    - 17
    - 21
    - 18
    - 20
    - 19
    - 15
    - 8
    - 14
    - 9
    - 13
    - 10
    - 12
    - 11
    - 7
    - 0
    - 6
    - 1
    - 5
    - 2
    - 4
    - 3
  analog:
    extReference: false
    type: "4067"
    inputVoltage: "3.3"
    multiplexers: 5
    pins:
      s0:
        port: "A"
        index: 7
      s1:
        port: "A"
        index: 10
      s2:
        port: "A"
        index: 6
      s3:
        port: "A"
        index: 15
      z0:
        port: "A"
        index: 2
      z1:
        port: "A"
        index: 3
      z2:
        port: "A"
        index: 4
      z3:
        port: "A"
        index: 5
      z4:
        port: "A"
        index: 1
    indexing:
    - 10
    - 11
    - 12
    - 13
    - 71
    - 8
    - 9
    - 14
    - 15
    - 70
    - 7
    - 6
    - 1
    - 0
    - 69
    - 5
    - 4
    - 3
    - 2
    - 68
    - 26
    - 27
    - 28
    - 29
    - 67
    - 24
    - 25
    - 30
    - 31
    - 66
    - 23
    - 22
    - 17
    - 16
    - 65
    - 21
    - 20
    - 19
    - 18
    - 64
    - 42
    - 43
    - 44
    - 45
    - 72
    - 40
    - 41
    - 46
    - 47
    - 73
    - 39
    - 38
    - 33
    - 32
    - 74
    - 37
    - 36
    - 35
    - 34
    - 75
    - 58
    - 59
    - 60
    - 61
    - 76
    - 56
    - 57
    - 62
    - 63
    - 77
    - 55
    - 54
    - 49
    - 48
    - 78
    - 53
    - 52
    - 51
    - 50
    - 79
  leds:
    external:
      type: "shiftRegister"
      shiftRegisters: 4
      invert: false
      pins:
        data:
          port: "B"
          index: 13
        clock:
          port: "B"
          index: 10
        latch:
          port: "B"
          index: 14
        enable:
          port: "B"
          index: 12
      indexing:
      - 4
      - 3
      - 5
      - 2
      - 6
      - 1
      - 7
      - 0
      - 12
      - 11
      - 13
      - 10
      - 14
      - 9
      - 15
      - 8
      - 20
      - 19
      - 21
      - 18
      - 22
      - 17
      - 23
      - 16
      - 28
      - 27
      - 29
      - 26
      - 30
      - 25
      - 31
      - 24
  bootloader:
    button:
      port: "C"
      index: 14