---
  mcu: "at90usb1286"
  extClockMhz: 16
  usb: true
  uart:
    dinMIDI:
      channel: 0
  i2c:
    display:
      channel: 0
  buttons:
    type: "native"
    pins:
    -
      port: "B"
      index: 6
    -
      port: "B"
      index: 5
    -
      port: "B"
      index: 4
    -
      port: "B"
      index: 3
    -
      port: "B"
      index: 2
    -
      port: "B"
      index: 1
    -
      port: "B"
      index: 0
    -
      port: "E"
      index: 7
    -
      port: "E"
      index: 6
    -
      port: "A"
      index: 0
    -
      port: "A"
      index: 5
    -
      port: "A"
      index: 1
    -
      port: "A"
      index: 6
    -
      port: "A"
      index: 2
    -
      port: "A"
      index: 7
    -
      port: "A"
      index: 3
  analog:
    type: "native"
    inputVoltage: "5.0"
    pins:
    -
      port: "F"
      index: 0
    -
      port: "F"
      index: 1
    -
      port: "F"
      index: 2
    -
      port: "F"
      index: 3
    -
      port: "F"
      index: 4
    -
      port: "F"
      index: 5
    -
      port: "F"
      index: 6
    -
      port: "F"
      index: 7
  leds:
    external:
      type: "native"
      pins:
      -
        port: "B"
        index: 7
      -
        port: "D"
        index: 4
      -
        port: "D"
        index: 5
      -
        port: "D"
        index: 6
      -
        port: "D"
        index: 7
      -
        port: "E"
        index: 0
      -
        port: "E"
        index: 1
      -
        port: "C"
        index: 0
      -
        port: "C"
        index: 1
      -
        port: "C"
        index: 2
      -
        port: "C"
        index: 3
      -
        port: "C"
        index: 4
      -
        port: "C"
        index: 5
      -
        port: "C"
        index: 6
      -
        port: "C"
        index: 7
      -
        port: "A"
        index: 4
  bootloader:
    button:
      port: "E"
      index: 4